### ISSUE TITLE
update ws version

### ISSUE THREAD

**Issue by dubanflorin** [roytan883/pomelo-rpc-ws#2]
Can you please update ws version because the current one has some security issues.
https://nodesecurity.io/advisories/550

**Comment by roytan883** [comment]
@dubanflorin Done, I updated ws to 3.3.1. Beware that I has not test it . So I hope you can give me some feedback if it can work. Thanks

**Comment by roytan883** [comment]
@dubanflorin 
please use pomelo-rpc-ws@1.0.3 and pomelo-rt@1.1.1
also add `process.EventEmitter = require('events');` at beginning

also you can use this demo: [chat](https://github.com/roytan883/chatofpomelo-rt)

**Comment by dubanflorin** [comment]
@roytan883 pomelo-rpc-ws@1.0.3 works for me

Thank you
